### 获取用户列表
GET http://127.0.0.1:33001/api/user/getUserList
Content-Type: application/json



### 获取用户详细信息
GET http://127.0.0.1:33001/api/user/getUserId
    ?userId=24209170533


### 获取用户信息，通过名字获取头像
GET http://127.0.0.1:33001/api/user/getUserPortraitByName
    ?userName=tingting

### 获取用户名
GET http://127.0.0.1:33001/api/user/getUserName
    ?userName=tingting
