/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./components/background.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PeopleRemainder: typeof import('./components/PeopleRemainder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timer: typeof import('./components/Timer.vue')['default']
  }
}
