/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/background.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PeopleRemainder: typeof import('./src/components/PeopleRemainder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedListsDialog: typeof import('./src/components/SavedListsDialog.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    TinyContainer: typeof import('@opentiny/vue')['Container']
    TinyLayout: typeof import('@opentiny/vue')['Layout']
  }
}
pentiny/vue')['Layout']
  }
}
