/* eslint-disable */
<<<<<<< HEAD
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

=======
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
>>>>>>> 1b6a0621026aa95b630a7ae359f5e7e7c40c3863
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/background.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PeopleRemainder: typeof import('./src/components/PeopleRemainder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedListsDialog: typeof import('./src/components/SavedListsDialog.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
<<<<<<< HEAD
    TinyContainer: typeof import('@opentiny/vue')['Container']
    TinyLayout: typeof import('@opentiny/vue')['Layout']
=======
>>>>>>> 1b6a0621026aa95b630a7ae359f5e7e7c40c3863
  }
}
